[package]
name = "readyset-clustertest"
version = "0.1.0"
publish = false
authors = ["ReadySet Technology, Inc. <info@readyset.io>"]
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["full"] }
futures = "0.3"
futures-util = "0.3"
anyhow = "1.0"
rand = "0.8.3"
url = "2.2.2"
mysql_async = { workspace = true }
tokio-postgres = { workspace = true }
envy = "0.4"
serde = { version = "1.0.8", features = ["derive"] }
hyper = "0.14.10"
bincode = "1.3.3"
tracing = { version = "0.1", features = ["release_max_level_debug"] }

# local deps
database-utils = { path = "../database-utils" }
nom-sql = { path = "../nom-sql" }
readyset-adapter = { path = "../readyset-adapter" }
readyset-client = { path = "../readyset-client", features = ["failure_injection"] }
readyset-data = { path = "../readyset-data" }
readyset-util = { path = "../readyset-util" }
readyset-tracing = { path = "../readyset-tracing" }
readyset-errors = { path = "../readyset-errors" }

[dev-dependencies]
serial_test = "0.5.1"
criterion = { version = "0.3", features=['real_blackbox', 'async_tokio']}
itertools = "0.10.4"
readyset-client-metrics = { path = "../readyset-client-metrics" }
test-utils = { path = "../test-utils" }
readyset-clustertest-macros = { path = "./macros" }
readyset-tracing = { path = "../readyset-tracing" }
rust_decimal = "1.26"

[[bench]]
name = "clustering"
harness = false

[features]
slow_bench = []
failure_injection = ["readyset-client/failure_injection"]
